

title: Who Built Bryn Mawr?

url: http://digbmc.github.io # https://wbbm.digitalprojects.brynmawr.edu
baseurl: /wbbm # /dev-2023

permalink: pretty

sass:
    sass_dir: _sass

collections:
  posts:
    output: true
    sort_by: date
    permalink: /:categories/blog/:year/:month/:day/:title/
  transcriptions:
    output: true

exclude:
 - README.md